name = “minzhangphoto-api”
main = “worker.js”
compatibility_date = “2024-12-01”


[vars]

# 你的网站域名（用于生成图片 URL）

PUBLIC_URL = “https://api.minzhangphoto.com” 


[[r2_buckets]]
binding = “PHOTO_BUCKET”
bucket_name = “minzhang-photos”  


[[kv_namespaces]]
binding = “CACHE_KV”
id = “853a82a58ab340b3b32eaeacd5971feb” 


# ============================================
